export const tableData = [
  { id: 1, user: "Alice", email: "aliceDallas@example.com" },
  { id: 2, user: "Bob", email: "bob@example.com" },
  { id: 3, user: "Charlie", email: "charlie@example.com" },
  {
    id: 4,
    user: "Jimi Hendrixxxxxxxxxxxxxxxx",
    email: "hendrix@example.com",
  },
  { id: 5, user: "Page", email: "zepp@example.com" },
  { id: 6, user: "", email: "alice@example.com" },
  { id: 7, user: "Bob", email: "bob@example.com" },
  { id: 8, user: "Charlie", email: "" },
  {
    id: 9,
    user: "Jimi Hendrixxxxxxxxxxxxxxxx",
    email: "hendrix@example.com",
  },
  { id: 10, user: "JohnLeeHooker", email: "Canned@heat.com" },
  { id: 16, user: "", email: "muddy@example.com" },
  { id: 17, user: "Howlin' Wolf", email: "" },
  { id: 18, user: "Elmore James", email: "slide@example.com" },
  { id: 19, user: "B.B. King", email: "bbking@example.com" },
  { id: 20, user: "T-Bone Walker", email: "tbone@example.com" },
  { id: 21, user: "Lightnin' Hopkins", email: "hopkins@example.com" },
  { id: 22, user: "Son House", email: "" },
  { id: 23, user: "", email: "robertjohnson@example.com" },
  { id: 24, user: "H. Sumlin", email: "boogie@chillen.com" },
];
