export const tableData = [
  { id: 1, user: "Alice", email: "aliceDallas@example.com", city: "Dallas" },
  { id: 2, user: "Bob", email: "bob@example.com", city: "Chicago" },
  { id: 3, user: "Charlie", email: "charlie@example.com", city: "Memphis" },
  {
    id: 4,
    user: "Jimi Hendrixxxxxxxxxxxxxxxx",
    email: "hendrix@example.com",
    city: "Seattle",
  },
  { id: 5, user: "Page", email: "zepp@example.com", city: "London" },
  { id: 6, user: "", email: "alice@example.com", city: "Houston" },
  { id: 7, user: "Bob", email: "bob@example.com", city: "Chicago" },
  { id: 8, user: "Charlie", email: "", city: "Memphis" },
  {
    id: 9,
    user: "Jimi Hendrixxxxxxxxxxxxxxxx",
    email: "hendrix@example.com",
    city: "Seattle",
  },
  { id: 10, user: "JohnLeeHooker", email: "Canned@heat.com", city: "Detroit" },
  {
    id: 11,
    user: "Janis Joplin",
    email: "janis@kozmic.com",
    city: "Port Arthur",
  },
  {
    id: 12,
    user: "Buddy Guy",
    email: "buddyg@example.com",
    city: "Lettsworth",
  },
  {
    id: 13,
    user: "Otis Rush",
    email: "rush@example.com",
    city: "Philadelphia",
  },
  { id: 14, user: "", email: "noName1@example.com", city: "Unknown" },
  {
    id: 15,
    user: "Eric Clapton",
    email: "slowhand@example.com",
    city: "Ripley",
  },
  { id: 16, user: "", email: "muddy@example.com", city: "Issaquena" },
  { id: 17, user: "Howlin' Wolf", email: "", city: "White Station" },
  {
    id: 18,
    user: "Elmore James",
    email: "slide@example.com",
    city: "Richland",
  },
  { id: 19, user: "B.B. King", email: "bbking@example.com", city: "Itta Bena" },
  { id: 20, user: "T-Bone Walker", email: "tbone@example.com", city: "Linden" },
  {
    id: 21,
    user: "Lightnin' Hopkins",
    email: "hopkins@example.com",
    city: "Centerville",
  },
  { id: 22, user: "Son House", email: "", city: "Riverton" },
  { id: 23, user: "", email: "robertjohnson@example.com", city: "Hazlehurst" },
  { id: 24, user: "H. Sumlin", email: "boogie@chillen.com", city: "Greenwood" },
  {
    id: 25,
    user: "Bonnie Raitt",
    email: "slidequeen@example.com",
    city: "Burbank",
  },
  {
    id: 26,
    user: "Albert King",
    email: "flyingv@example.com",
    city: "Indianola",
  },
  { id: 27, user: "Stevie Ray", email: "srv@example.com", city: "Dallas" },
  {
    id: 28,
    user: "Joe Bonamassa",
    email: "jb@example.com",
    city: "New Hartford",
  },
  {
    id: 29,
    user: "Gary Clark Jr.",
    email: "gclark@example.com",
    city: "Austin",
  },
  { id: 30, user: "", email: "nameless@example.com", city: "Unknown" },
  {
    id: 31,
    user: "Freddie King",
    email: "texascannonball@example.com",
    city: "Gilmer",
  },
  { id: 32, user: "Koko Taylor", email: "", city: "Memphis" },
  {
    id: 33,
    user: "Muddy Waters",
    email: "muddyw@example.com",
    city: "Clarksdale",
  },
  {
    id: 34,
    user: "Little Walter",
    email: "harpblow@example.com",
    city: "Marksville",
  },
  {
    id: 35,
    user: "Willie Dixon",
    email: "bluesman@example.com",
    city: "Vicksburg",
  },
  { id: 36, user: "Big Mama Thornton", email: "", city: "Ariton" },
  {
    id: 37,
    user: "Johnny Winter",
    email: "firenice@example.com",
    city: "Beaumont",
  },
  {
    id: 38,
    user: "R.L. Burnside",
    email: "burnside@example.com",
    city: "Harmontown",
  },
  {
    id: 39,
    user: "Clarence Gatemouth",
    email: "brown@example.com",
    city: "Vinton",
  },
];
